config/routes.rb
D3::Application.routes.draw do
  resources :users

  resources :items

  resources :user_sessions

  root :to => 'items#index'

  match "login", :to => "user_sessions#new", :as => "login"
  match "logout", :to => "user_sessions#destroy", :as => "logout"
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :minlevel, :description, :player_class, :slot, :minstat, :maxstat
  validates :name, :presence => true
  validates :minlevel, :numericality => {:only_integer=> true,
		:greater_than => -1,
		:less_than => 61}
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic
  attr_accessible :username, :email, :battlenet, :password, :password_confirmation
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

helper_method :current_user

private

	def current_user_session
  		return @current_user_session if defined?(@current_user_session)
  			@current_user_session = UserSession.find
	end

	def current_user
  	return @current_user if defined?(@current_user)
  		@current_user = current_user_session && current_user_session.record
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @Armor = Item.find_all_by_slot(['Head', 'Shoulders', 'Torso', 'Wrists', 'Hands', 'Waist', 'Legs', 'Feet', 'Off-Hand'])
    @Weapon = Item.find_all_by_slot(['One-Handed', 'Two-Handed', 'Ranged'])
    @Other = Item.find_all_by_slot(['Jewlery', 'Follower Special', 'Consumable', 'Crafting'])
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    if params[:item][:minlevel] == ""
      params[:item][:minlevel] = 0
    end
    @item = Item.new(params[:item])
    if @item.save
      redirect_to items_path, :notice => "Successfully Created an Item"
    else
      flash[:message] = @item.errors.to_a.join(" ")
      render :action =>'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params[:item])
      redirect_to @item, :notice  => "Successfully updated item."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_url, :notice => "Successfully destroyed item."
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  # GET /user_sessions/new
  # GET /user_sessions/new.json
  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_session }
    end
  end

  # POST /user_sessions
  # POST /user_sessions.json
  def create
    @user_session = UserSession.new(params[:user_session])

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to items_path, notice: 'Login Successful.' }
        format.json { render json: items_path, status: :created, location: @user_session }
      else
        format.html { render action: "new" }
        format.json { render json: @user_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.json
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to items_path, :notice => 'Logout Successful' }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Account Registered"
    else
      flash[:message] = @user.errors.to_a.join(" ")
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice  => "Successfully updated profile."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <p>
    <%= f.label :name %> <i>(required)</i> <br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Requires_Level %><br />
    <%= f.number_field :minlevel%>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :Requires_Class %><br />
    <%= f.select :player_class, options_for_select(['None', 'Barbarian', 'Demon Hunter', 'Monk', 'Witch Doctor', 'Wizard']) %>
  </p>
  <p>
    <%= f.label :slot %><br />
    <%= f.select :slot, options_for_select(['Head', 'Shoulders', 'Torso', 'Wrists', 'Hands', 'Waist', 'Legs', 'Feet', 'Jewlery', 'Off-Hand', 'Follower Special', 'One-Handed', 'Two-Handed', 'Ranged', 'Consumable', 'Crafting']) %>
  </p>
  <p>
    <%= f.label :Armor %><br />
    <%= f.number_field :minstat %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>
<div id="notice"><%=flash[:message] %></div>
<%= render 'form' %>

<p>
  <%= link_to "Show", @item %> |
  <%= link_to "View All", items_path %>
</p>

app/views/items/index.html.erb
<div class=notice><%=flash[:notice] %></div>
<h1>Items</h1>
<h2>Armor</h2>
<table id=items>
  <tr>
    <th>Name</th>
    <th>Required Level</th>
    <th>Description</th>
    <th>Required Class</th>
    <th>Slot</th>
    <th>Armor</th>
  </tr>
  <% for item in @Armor %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.minlevel %></td>
      <td><%= item.description %></td>
      <td><%= item.player_class %></td>
      <td><%= item.slot %></td>
      <td><%= item.minstat %></td>
      <td><%= link_to "Show", item %></td>
      <td><%= link_to "Edit", edit_item_path(item) %></td>
      <td><%= link_to "Destroy", item, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<h2>Weapons</h2>
<table id=items>
  <tr>
    <th>Name</th>
    <th>Required Level</th>
    <th>Description</th>
    <th>Required Class</th>
    <th>Slot</th>
    <th>Damage</th>
  </tr>
  <% for item in @Weapon %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.minlevel %></td>
      <td><%= item.description %></td>
      <td><%= item.player_class %></td>
      <td><%= item.slot %></td>
      <td><%= item.minstat %></td>
      <td><%= link_to "Show", item %></td>
      <td><%= link_to "Edit", edit_item_path(item) %></td>
      <td><%= link_to "Destroy", item, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<h2>Other</h2>
<table id=items>
  <tr>
    <th>Name</th>
    <th>Required Level</th>
    <th>Description</th>
    <th>Required Class</th>
    <th>Slot</th>
  </tr>
  <% for item in @Other %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.minlevel %></td>
      <td><%= item.description %></td>
      <td><%= item.player_class %></td>
      <td><%= item.slot %></td>
      <td><%= link_to "Show", item %></td>
      <td><%= link_to "Edit", edit_item_path(item) %></td>
      <td><%= link_to "Destroy", item, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Item", new_item_path %></p>

app/views/items/new.html.erb
<h1>New Item</h1>
<div class=notice><%=flash[:message] %></div>
<%= render 'form' %>

<p><%= link_to "Back to List", items_path %></p>

app/views/items/show.html.erb
<h1>Item</h1>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>
<p>
  <strong>Required Level:</strong>
  <%= @item.minlevel %>
</p>
<p>
  <strong>Item Description:</strong>
  <%= @item.description %>
</p>
<p>
  <strong>Required Class:</strong>
  <%= @item.player_class %>
</p>
<p>
  <strong>Slot:</strong>
  <%= @item.slot %>
</p>
<p>
  <strong>Min Stat:</strong>
  <%= @item.minstat %>
</p>
<p>
  <strong>Max Stat:</strong>
  <%= @item.maxstat %>
</p>

<p>
  <%= link_to "Edit", edit_item_path(@item) %> |
  <%= link_to "Destroy", @item, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", items_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D3 Item Sharing</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if current_user %>
    <%= link_to "Edit Profile", edit_user_path(:current) %> |
    <%= link_to "Logout", logout_path %>
  <% else %>
    <%= link_to "Register", new_user_path %> |
    <%= link_to "Login", login_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.username %></td>
    <td><%= user_session.password %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User session', new_user_session_path %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :Battlenet_Name %><br />
    <%= f.text_field :battlenet %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
    <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>New User</h1>
<div class=notice><%=flash[:message] %></div>
<%= render 'form' %>